### ISSUE TITLE
Hardware required for the package

### ISSUE THREAD

**Issue by kishorekumar29** [radoi90/Turtlebot-track#1]
I am going to build my own robot for line following. As of now only the line following is required. So what are all the hardware required to build the line following robot in ROS and install your code (only line following code)

**Comment by radoi90** [comment]
- a machine with ROS installed to run the code (I had a netbook with Atom processor)
- a video input device (I had a Logitech webcam, VGA resolution)
- (optional) a robot compatible with ROS (I had a Turtlebot)
